const f = () => {

  try {
    let a = 12;
    // console.log(program)
    console.log("Program ran successfully")
    return
  }
  catch (error) {
    console.log("This is an Error")
    console.log(p)
  }

  // finally be like "mujhe chalte rahena hei"

  finally {      // code will always run like modiji
    console.log("I am a good coder")
    // Close the file
    // Exit the Loop
    // Break the chain
    // Write to the log file
    // finally does cleanup
  }
}

f()

console.log("End")